name: JWGerold
favicon: null
layout_spectrum: 0.6369510609656572
typography_spectrum: 0.04558144463226199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.02445503370836377
  lightness: 0.6885251859202981
  saturation: 0.3755070164334029
  rhythmicContrast: 0.768168865935877
purpose: []
